import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../redux/store';
import { userApi } from 'apis/userApi';

export interface UserSlice {
  listUser: any;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: UserSlice = {
  listUser: {},
  status: 'idle',
};

export const signIn = createAsyncThunk('user/signIn', async () => {
  const response = await userApi.signIn({
    email: 'system@free-agent-east.com',
    password: 'admin1234567',
  });
  const { accessToken } = response.data;
  localStorage.setItem('token', accessToken);
  return response.data;
});

export const fetchListUser = createAsyncThunk(
  'user/fetchListUser',
  async () => {
    const response = await userApi.getListUser();
    return response.data;
  }
);

export const usersSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchListUser.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchListUser.fulfilled, (state, { payload }) => {
        state.status = 'idle';
        state.listUser = payload;
      })
      .addCase(signIn.pending, (state, { payload }) => {
        state.status = 'loading';
      })
      .addCase(signIn.fulfilled, (state, { payload }) => {
        state.status = 'idle';
      });
  },
});

export const getListUser = (state: RootState) => state.user?.listUser;

// export const { increment, decrement, incrementByAmount } = usersSlice.actions;

export default usersSlice.reducer;
